// ----------------------------------------------------------------------------------------
// This file has been automatically generated by a tool and should not be changed manually.
// ----------------------------------------------------------------------------------------
namespace Sirenix.OdinInspector.GeneratedEditors
{
    extern alias Assembly30a7778f00184f888d1e28fea4755360;
    extern alias Assemblycee486461ae44051aeac11756f0395b9;
    extern alias Assembly914617a2c8954e42a26457ad5421320d;
    using System.Runtime.CompilerServices;
    using UnityEditor;
    
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::AlwaysForward), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_AlwaysForward_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::ConstForce), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_ConstForce_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::DestroyAfterTime), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_DestroyAfterTime_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Enemy), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Enemy_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::ExampleWheelController), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_ExampleWheelController_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::FPSController), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_FPSController_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::FPSWeaponTrigger), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_FPSWeaponTrigger_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::GameManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_GameManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::MouseFollower), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_MouseFollower_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Orbiter), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Orbiter_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::PitchShifter), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_PitchShifter_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::ProjectileDragging), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_ProjectileDragging_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::ProjectileFollow), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_ProjectileFollow_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Resetter), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Resetter_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::StringMemberHelperExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_StringMemberHelperExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::TankAlwaysForward), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_TankAlwaysForward_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::TankController), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_TankController_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::TankProjectile), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_TankProjectile_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::TankTranslator), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_TankTranslator_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::TankWeaponController), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_TankWeaponController_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::TargetDamage), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_TargetDamage_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::UIManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_UIManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.AssetListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_AssetListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.BoxGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_BoxGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ButtonAndButtonGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ButtonAndButtonGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ColorPaletteExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ColorPaletteExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ContextExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ContextExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.CustomContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_CustomContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.CustomDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_CustomDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.CustomGroupExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_CustomGroupExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.DictionaryExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_DictionaryExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.DisableAndDisabledIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_DisableAndDisabledIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.DisableContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_DisableContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.DisableInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_DisableInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.DisplayAsStringExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_DisplayAsStringExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.EnumToggleButtonsExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_EnumToggleButtonsExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.FoldoutGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_FoldoutGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.GenericDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_GenericDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.GenericMenuExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_GenericMenuExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.GUIColorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_GUIColorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.HealthBarExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_HealthBarExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.HideInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_HideInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.HideLabelExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_HideLabelExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.HideReferenceObjectPickerExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_HideReferenceObjectPickerExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.HorizontalGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_HorizontalGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples1), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples1_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.IncorrectUseOfOdinSerializeAttributeExamples2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_IncorrectUseOfOdinSerializeAttributeExamples2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.IndentExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_IndentExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.InfoBoxExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_InfoBoxExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.InlineEditorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_InlineEditorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.LabelTextExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_LabelTextExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.MinMaxSliderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_MinMaxSliderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.MinMaxValueValueExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_MinMaxValueValueExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.MultiLinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_MultiLinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.NoBoilerplate), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_NoBoilerplate_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ObjectPlacer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ObjectPlacer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.OnInspectorGUIExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_OnInspectorGUIExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.OnValueChangedExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_OnValueChangedExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.PlaceableObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_PlaceableObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.PrefabOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_PrefabOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.PriorityExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_PriorityExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.PropertyOrderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_PropertyOrderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.PropertyTooltipExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_PropertyTooltipExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.QuaternionAndVectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_QuaternionAndVectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ReadOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ReadOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ReflectionExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ReflectionExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.RequiredExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_RequiredExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.SceneAndAssetsOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_SceneAndAssetsOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.SerializeAnything), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_SerializeAnything_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ShowAndHideIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ShowAndHideIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ShowInInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ShowInInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.TabExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_TabExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.TitleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_TitleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ToggleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ToggleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ToggleLeftExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ToggleLeftExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ValidateInputExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ValidateInputExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ValidationExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ValidationExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.ValueDropdownExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_ValueDropdownExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly30a7778f00184f888d1e28fea4755360::Sirenix.OdinInspector.Demos.WrapExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly30a7778f00184f888d1e28fea4755360_Sirenix_OdinInspector_Demos_WrapExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblycee486461ae44051aeac11756f0395b9::Sirenix.OdinInspector.Editor.ColorPaletteManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblycee486461ae44051aeac11756f0395b9_Sirenix_OdinInspector_Editor_ColorPaletteManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblycee486461ae44051aeac11756f0395b9::Sirenix.OdinInspector.Editor.GeneralDrawerConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblycee486461ae44051aeac11756f0395b9_Sirenix_OdinInspector_Editor_GeneralDrawerConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblycee486461ae44051aeac11756f0395b9::Sirenix.OdinInspector.Editor.InspectorConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblycee486461ae44051aeac11756f0395b9_Sirenix_OdinInspector_Editor_InspectorConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly914617a2c8954e42a26457ad5421320d::Sirenix.Serialization.GlobalSerializationConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly914617a2c8954e42a26457ad5421320d_Sirenix_Serialization_GlobalSerializationConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
}
